# These are supported funding model platforms

github: [ayusingh-54]
# patreon: your-patreon
# open_collective: your-collective
# ko_fi: your-kofi
# tidelift: npm/package-name
# community_bridge: your-project
# liberapay: your-liberapay
# issuehunt: your-issuehunt
# otechie: your-otechie
# lfx_crowdfunding: your-project-name
custom: ["https://buymeacoffee.com/ayusingh54"]
